name: datamap-publish-to-pypi

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install poetry
      run: python -m pip install poetry

    - name: Setup poetry for publish
      run: |
        python -m poetry build
        python -m poetry config pypi-token.pypi {{ $secrets.PYPI_API_TOKEN }}

    - name: Publish to pypi.org
      run: |
        python -m poetry publish --username __token__ --password {{ $secrets.PYPI_API_TOKEN }}
