name: datamap-publish-to-pypi

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install poetry
      run: python -m pip install poetry

    - name: Setup poetry for publish
      run: |
        python -m poetry build
        python -m poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish to pypi.org
      run: |
        python -m python -m poetry publish --no-interaction
